package cn.com.helloclyde.ygoService.mapper.persistence;

import cn.com.helloclyde.ygoService.mapper.model.Config;
import cn.com.helloclyde.ygoService.mapper.model.ConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int countByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int deleteByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int deleteByPrimaryKey(String mKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int insert(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int insertSelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    List<Config> selectByExampleWithBLOBs(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    List<Config> selectByExample(ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    Config selectByPrimaryKey(String mKey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int updateByExample(@Param("record") Config record, @Param("example") ConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int updateByPrimaryKeySelective(Config record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Config record);
}