package cn.com.helloclyde.ygoOnline.mapper.user.model;

import com.google.gson.Gson;

import java.util.ArrayList;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cards
     *
     * @mbggenerated Mon Jan 30 11:19:35 CST 2017
     */
    private String cards = new Gson().toJson(new ArrayList<>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_packages
     *
     * @mbggenerated Mon Jan 30 11:19:35 CST 2017
     */
    private String cardPackages = new Gson().toJson(new ArrayList<>());

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cards
     *
     * @return the value of user.cards
     *
     * @mbggenerated Mon Jan 30 11:19:35 CST 2017
     */
    public String getCards() {
        return cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cards
     *
     * @param cards the value for user.cards
     *
     * @mbggenerated Mon Jan 30 11:19:35 CST 2017
     */
    public void setCards(String cards) {
        this.cards = cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_packages
     *
     * @return the value of user.card_packages
     *
     * @mbggenerated Mon Jan 30 11:19:35 CST 2017
     */
    public String getCardPackages() {
        return cardPackages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_packages
     *
     * @param cardPackages the value for user.card_packages
     *
     * @mbggenerated Mon Jan 30 11:19:35 CST 2017
     */
    public void setCardPackages(String cardPackages) {
        this.cardPackages = cardPackages;
    }
}