package cn.com.helloclyde.ygoService.mapper.model;

import java.util.ArrayList;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMKeyIsNull() {
            addCriterion("m_key is null");
            return (Criteria) this;
        }

        public Criteria andMKeyIsNotNull() {
            addCriterion("m_key is not null");
            return (Criteria) this;
        }

        public Criteria andMKeyEqualTo(String value) {
            addCriterion("m_key =", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotEqualTo(String value) {
            addCriterion("m_key <>", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyGreaterThan(String value) {
            addCriterion("m_key >", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyGreaterThanOrEqualTo(String value) {
            addCriterion("m_key >=", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyLessThan(String value) {
            addCriterion("m_key <", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyLessThanOrEqualTo(String value) {
            addCriterion("m_key <=", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyLike(String value) {
            addCriterion("m_key like", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotLike(String value) {
            addCriterion("m_key not like", value, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyIn(List<String> values) {
            addCriterion("m_key in", values, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotIn(List<String> values) {
            addCriterion("m_key not in", values, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyBetween(String value1, String value2) {
            addCriterion("m_key between", value1, value2, "mKey");
            return (Criteria) this;
        }

        public Criteria andMKeyNotBetween(String value1, String value2) {
            addCriterion("m_key not between", value1, value2, "mKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated do_not_delete_during_merge Sat Mar 18 13:46:03 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}