package cn.com.helloclyde.ygoService.mapper.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.m_key
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    private String mKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.m_key
     *
     * @return the value of config.m_key
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public String getmKey() {
        return mKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.m_key
     *
     * @param mKey the value for config.m_key
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public void setmKey(String mKey) {
        this.mKey = mKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbggenerated Sat Mar 18 13:46:03 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }
}