package cn.com.helloclyde.ygoService.mapper.model;

public class Config {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.key
     *
     * @mbggenerated Fri Mar 17 15:40:38 CST 2017
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config.value
     *
     * @mbggenerated Fri Mar 17 15:40:38 CST 2017
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.key
     *
     * @return the value of config.key
     *
     * @mbggenerated Fri Mar 17 15:40:38 CST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.key
     *
     * @param key the value for config.key
     *
     * @mbggenerated Fri Mar 17 15:40:38 CST 2017
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config.value
     *
     * @return the value of config.value
     *
     * @mbggenerated Fri Mar 17 15:40:38 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config.value
     *
     * @param value the value for config.value
     *
     * @mbggenerated Fri Mar 17 15:40:38 CST 2017
     */
    public void setValue(String value) {
        this.value = value;
    }
}