package cn.com.helloclyde.ygoService.mapper.model;

public class UserWithBLOBs extends User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.cards
     *
     * @mbggenerated Fri Mar 03 11:38:07 CST 2017
     */
    private String cards;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.card_packages
     *
     * @mbggenerated Fri Mar 03 11:38:07 CST 2017
     */
    private String cardPackages;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.cards
     *
     * @return the value of user.cards
     *
     * @mbggenerated Fri Mar 03 11:38:07 CST 2017
     */
    public String getCards() {
        return cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.cards
     *
     * @param cards the value for user.cards
     *
     * @mbggenerated Fri Mar 03 11:38:07 CST 2017
     */
    public void setCards(String cards) {
        this.cards = cards;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.card_packages
     *
     * @return the value of user.card_packages
     *
     * @mbggenerated Fri Mar 03 11:38:07 CST 2017
     */
    public String getCardPackages() {
        return cardPackages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.card_packages
     *
     * @param cardPackages the value for user.card_packages
     *
     * @mbggenerated Fri Mar 03 11:38:07 CST 2017
     */
    public void setCardPackages(String cardPackages) {
        this.cardPackages = cardPackages;
    }
}