package cn.com.helloclyde.ygoService.mapper.model;

public class YgodataWithBLOBs extends Ygodata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardPhAl
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardphal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardCamp
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardcamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.JPCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String jpcardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardName2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardname2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.JPCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String jpcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.JPDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String jpdcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String scdcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tcdcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String endcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.JPCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String jpcardrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccardrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccardrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardrace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardBagNum
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardbagnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.JPCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String jpcardattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccardattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccardattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccardrare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccardrare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardrare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardAtk2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardatk2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardDef2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String carddef2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.JPCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String jpcarddepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccarddepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccarddepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encarddepict;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.SCCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String sccardban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.TCCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String tccardban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.ENCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String encardban;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardIsCZN
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardisczn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardPass
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardpass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardAdjust
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardadjust;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardUnion
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardunion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardOnceName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardoncename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardAbbrName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardabbrname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardEfficeType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private String cardefficetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardPhAl
     *
     * @return the value of ygodata.CardPhAl
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardphal() {
        return cardphal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardPhAl
     *
     * @param cardphal the value for ygodata.CardPhAl
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardphal(String cardphal) {
        this.cardphal = cardphal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardCamp
     *
     * @return the value of ygodata.CardCamp
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardcamp() {
        return cardcamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardCamp
     *
     * @param cardcamp the value for ygodata.CardCamp
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardcamp(String cardcamp) {
        this.cardcamp = cardcamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.JPCardName
     *
     * @return the value of ygodata.JPCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getJpcardname() {
        return jpcardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.JPCardName
     *
     * @param jpcardname the value for ygodata.JPCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setJpcardname(String jpcardname) {
        this.jpcardname = jpcardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardName
     *
     * @return the value of ygodata.SCCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccardname() {
        return sccardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardName
     *
     * @param sccardname the value for ygodata.SCCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccardname(String sccardname) {
        this.sccardname = sccardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardName
     *
     * @return the value of ygodata.TCCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccardname() {
        return tccardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardName
     *
     * @param tccardname the value for ygodata.TCCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccardname(String tccardname) {
        this.tccardname = tccardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardName
     *
     * @return the value of ygodata.ENCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardname() {
        return encardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardName
     *
     * @param encardname the value for ygodata.ENCardName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardname(String encardname) {
        this.encardname = encardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardName2
     *
     * @return the value of ygodata.ENCardName2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardname2() {
        return encardname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardName2
     *
     * @param encardname2 the value for ygodata.ENCardName2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardname2(String encardname2) {
        this.encardname2 = encardname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.JPCardType
     *
     * @return the value of ygodata.JPCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getJpcardtype() {
        return jpcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.JPCardType
     *
     * @param jpcardtype the value for ygodata.JPCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setJpcardtype(String jpcardtype) {
        this.jpcardtype = jpcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardType
     *
     * @return the value of ygodata.SCCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccardtype() {
        return sccardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardType
     *
     * @param sccardtype the value for ygodata.SCCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccardtype(String sccardtype) {
        this.sccardtype = sccardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardType
     *
     * @return the value of ygodata.TCCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccardtype() {
        return tccardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardType
     *
     * @param tccardtype the value for ygodata.TCCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccardtype(String tccardtype) {
        this.tccardtype = tccardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardType
     *
     * @return the value of ygodata.ENCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardtype() {
        return encardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardType
     *
     * @param encardtype the value for ygodata.ENCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardtype(String encardtype) {
        this.encardtype = encardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.JPDCardType
     *
     * @return the value of ygodata.JPDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getJpdcardtype() {
        return jpdcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.JPDCardType
     *
     * @param jpdcardtype the value for ygodata.JPDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setJpdcardtype(String jpdcardtype) {
        this.jpdcardtype = jpdcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCDCardType
     *
     * @return the value of ygodata.SCDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getScdcardtype() {
        return scdcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCDCardType
     *
     * @param scdcardtype the value for ygodata.SCDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setScdcardtype(String scdcardtype) {
        this.scdcardtype = scdcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCDCardType
     *
     * @return the value of ygodata.TCDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTcdcardtype() {
        return tcdcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCDCardType
     *
     * @param tcdcardtype the value for ygodata.TCDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTcdcardtype(String tcdcardtype) {
        this.tcdcardtype = tcdcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENDCardType
     *
     * @return the value of ygodata.ENDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEndcardtype() {
        return endcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENDCardType
     *
     * @param endcardtype the value for ygodata.ENDCardType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEndcardtype(String endcardtype) {
        this.endcardtype = endcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.JPCardRace
     *
     * @return the value of ygodata.JPCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getJpcardrace() {
        return jpcardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.JPCardRace
     *
     * @param jpcardrace the value for ygodata.JPCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setJpcardrace(String jpcardrace) {
        this.jpcardrace = jpcardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardRace
     *
     * @return the value of ygodata.SCCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccardrace() {
        return sccardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardRace
     *
     * @param sccardrace the value for ygodata.SCCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccardrace(String sccardrace) {
        this.sccardrace = sccardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardRace
     *
     * @return the value of ygodata.TCCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccardrace() {
        return tccardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardRace
     *
     * @param tccardrace the value for ygodata.TCCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccardrace(String tccardrace) {
        this.tccardrace = tccardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardRace
     *
     * @return the value of ygodata.ENCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardrace() {
        return encardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardRace
     *
     * @param encardrace the value for ygodata.ENCardRace
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardrace(String encardrace) {
        this.encardrace = encardrace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardBagNum
     *
     * @return the value of ygodata.CardBagNum
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardbagnum() {
        return cardbagnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardBagNum
     *
     * @param cardbagnum the value for ygodata.CardBagNum
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardbagnum(String cardbagnum) {
        this.cardbagnum = cardbagnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.JPCardAttribute
     *
     * @return the value of ygodata.JPCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getJpcardattribute() {
        return jpcardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.JPCardAttribute
     *
     * @param jpcardattribute the value for ygodata.JPCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setJpcardattribute(String jpcardattribute) {
        this.jpcardattribute = jpcardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardAttribute
     *
     * @return the value of ygodata.SCCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccardattribute() {
        return sccardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardAttribute
     *
     * @param sccardattribute the value for ygodata.SCCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccardattribute(String sccardattribute) {
        this.sccardattribute = sccardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardAttribute
     *
     * @return the value of ygodata.TCCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccardattribute() {
        return tccardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardAttribute
     *
     * @param tccardattribute the value for ygodata.TCCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccardattribute(String tccardattribute) {
        this.tccardattribute = tccardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardAttribute
     *
     * @return the value of ygodata.ENCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardattribute() {
        return encardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardAttribute
     *
     * @param encardattribute the value for ygodata.ENCardAttribute
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardattribute(String encardattribute) {
        this.encardattribute = encardattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardRare
     *
     * @return the value of ygodata.SCCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccardrare() {
        return sccardrare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardRare
     *
     * @param sccardrare the value for ygodata.SCCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccardrare(String sccardrare) {
        this.sccardrare = sccardrare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardRare
     *
     * @return the value of ygodata.TCCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccardrare() {
        return tccardrare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardRare
     *
     * @param tccardrare the value for ygodata.TCCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccardrare(String tccardrare) {
        this.tccardrare = tccardrare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardRare
     *
     * @return the value of ygodata.ENCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardrare() {
        return encardrare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardRare
     *
     * @param encardrare the value for ygodata.ENCardRare
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardrare(String encardrare) {
        this.encardrare = encardrare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardAtk2
     *
     * @return the value of ygodata.CardAtk2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardatk2() {
        return cardatk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardAtk2
     *
     * @param cardatk2 the value for ygodata.CardAtk2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardatk2(String cardatk2) {
        this.cardatk2 = cardatk2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardDef2
     *
     * @return the value of ygodata.CardDef2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCarddef2() {
        return carddef2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardDef2
     *
     * @param carddef2 the value for ygodata.CardDef2
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCarddef2(String carddef2) {
        this.carddef2 = carddef2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.JPCardDepict
     *
     * @return the value of ygodata.JPCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getJpcarddepict() {
        return jpcarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.JPCardDepict
     *
     * @param jpcarddepict the value for ygodata.JPCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setJpcarddepict(String jpcarddepict) {
        this.jpcarddepict = jpcarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardDepict
     *
     * @return the value of ygodata.SCCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccarddepict() {
        return sccarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardDepict
     *
     * @param sccarddepict the value for ygodata.SCCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccarddepict(String sccarddepict) {
        this.sccarddepict = sccarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardDepict
     *
     * @return the value of ygodata.TCCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccarddepict() {
        return tccarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardDepict
     *
     * @param tccarddepict the value for ygodata.TCCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccarddepict(String tccarddepict) {
        this.tccarddepict = tccarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardDepict
     *
     * @return the value of ygodata.ENCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncarddepict() {
        return encarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardDepict
     *
     * @param encarddepict the value for ygodata.ENCardDepict
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncarddepict(String encarddepict) {
        this.encarddepict = encarddepict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.SCCardBan
     *
     * @return the value of ygodata.SCCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getSccardban() {
        return sccardban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.SCCardBan
     *
     * @param sccardban the value for ygodata.SCCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setSccardban(String sccardban) {
        this.sccardban = sccardban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.TCCardBan
     *
     * @return the value of ygodata.TCCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getTccardban() {
        return tccardban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.TCCardBan
     *
     * @param tccardban the value for ygodata.TCCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setTccardban(String tccardban) {
        this.tccardban = tccardban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.ENCardBan
     *
     * @return the value of ygodata.ENCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getEncardban() {
        return encardban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.ENCardBan
     *
     * @param encardban the value for ygodata.ENCardBan
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setEncardban(String encardban) {
        this.encardban = encardban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardIsCZN
     *
     * @return the value of ygodata.CardIsCZN
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardisczn() {
        return cardisczn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardIsCZN
     *
     * @param cardisczn the value for ygodata.CardIsCZN
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardisczn(String cardisczn) {
        this.cardisczn = cardisczn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardPass
     *
     * @return the value of ygodata.CardPass
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardpass() {
        return cardpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardPass
     *
     * @param cardpass the value for ygodata.CardPass
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardpass(String cardpass) {
        this.cardpass = cardpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardAdjust
     *
     * @return the value of ygodata.CardAdjust
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardadjust() {
        return cardadjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardAdjust
     *
     * @param cardadjust the value for ygodata.CardAdjust
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardadjust(String cardadjust) {
        this.cardadjust = cardadjust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardUnion
     *
     * @return the value of ygodata.CardUnion
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardunion() {
        return cardunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardUnion
     *
     * @param cardunion the value for ygodata.CardUnion
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardunion(String cardunion) {
        this.cardunion = cardunion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardOnceName
     *
     * @return the value of ygodata.CardOnceName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardoncename() {
        return cardoncename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardOnceName
     *
     * @param cardoncename the value for ygodata.CardOnceName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardoncename(String cardoncename) {
        this.cardoncename = cardoncename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardAbbrName
     *
     * @return the value of ygodata.CardAbbrName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardabbrname() {
        return cardabbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardAbbrName
     *
     * @param cardabbrname the value for ygodata.CardAbbrName
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardabbrname(String cardabbrname) {
        this.cardabbrname = cardabbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardEfficeType
     *
     * @return the value of ygodata.CardEfficeType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getCardefficetype() {
        return cardefficetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardEfficeType
     *
     * @param cardefficetype the value for ygodata.CardEfficeType
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardefficetype(String cardefficetype) {
        this.cardefficetype = cardefficetype;
    }
}