package cn.com.helloclyde.ygoService.mapper.model;

import java.util.ArrayList;
import java.util.List;

public class YgodataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public YgodataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCardidIsNull() {
            addCriterion("CardID is null");
            return (Criteria) this;
        }

        public Criteria andCardidIsNotNull() {
            addCriterion("CardID is not null");
            return (Criteria) this;
        }

        public Criteria andCardidEqualTo(Integer value) {
            addCriterion("CardID =", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotEqualTo(Integer value) {
            addCriterion("CardID <>", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThan(Integer value) {
            addCriterion("CardID >", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardID >=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThan(Integer value) {
            addCriterion("CardID <", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidLessThanOrEqualTo(Integer value) {
            addCriterion("CardID <=", value, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidIn(List<Integer> values) {
            addCriterion("CardID in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotIn(List<Integer> values) {
            addCriterion("CardID not in", values, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidBetween(Integer value1, Integer value2) {
            addCriterion("CardID between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardidNotBetween(Integer value1, Integer value2) {
            addCriterion("CardID not between", value1, value2, "cardid");
            return (Criteria) this;
        }

        public Criteria andCardstarnumIsNull() {
            addCriterion("CardStarNum is null");
            return (Criteria) this;
        }

        public Criteria andCardstarnumIsNotNull() {
            addCriterion("CardStarNum is not null");
            return (Criteria) this;
        }

        public Criteria andCardstarnumEqualTo(Integer value) {
            addCriterion("CardStarNum =", value, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumNotEqualTo(Integer value) {
            addCriterion("CardStarNum <>", value, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumGreaterThan(Integer value) {
            addCriterion("CardStarNum >", value, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardStarNum >=", value, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumLessThan(Integer value) {
            addCriterion("CardStarNum <", value, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumLessThanOrEqualTo(Integer value) {
            addCriterion("CardStarNum <=", value, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumIn(List<Integer> values) {
            addCriterion("CardStarNum in", values, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumNotIn(List<Integer> values) {
            addCriterion("CardStarNum not in", values, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumBetween(Integer value1, Integer value2) {
            addCriterion("CardStarNum between", value1, value2, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardstarnumNotBetween(Integer value1, Integer value2) {
            addCriterion("CardStarNum not between", value1, value2, "cardstarnum");
            return (Criteria) this;
        }

        public Criteria andCardatkIsNull() {
            addCriterion("CardAtk is null");
            return (Criteria) this;
        }

        public Criteria andCardatkIsNotNull() {
            addCriterion("CardAtk is not null");
            return (Criteria) this;
        }

        public Criteria andCardatkEqualTo(Integer value) {
            addCriterion("CardAtk =", value, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkNotEqualTo(Integer value) {
            addCriterion("CardAtk <>", value, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkGreaterThan(Integer value) {
            addCriterion("CardAtk >", value, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardAtk >=", value, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkLessThan(Integer value) {
            addCriterion("CardAtk <", value, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkLessThanOrEqualTo(Integer value) {
            addCriterion("CardAtk <=", value, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkIn(List<Integer> values) {
            addCriterion("CardAtk in", values, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkNotIn(List<Integer> values) {
            addCriterion("CardAtk not in", values, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkBetween(Integer value1, Integer value2) {
            addCriterion("CardAtk between", value1, value2, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCardatkNotBetween(Integer value1, Integer value2) {
            addCriterion("CardAtk not between", value1, value2, "cardatk");
            return (Criteria) this;
        }

        public Criteria andCarddefIsNull() {
            addCriterion("CardDef is null");
            return (Criteria) this;
        }

        public Criteria andCarddefIsNotNull() {
            addCriterion("CardDef is not null");
            return (Criteria) this;
        }

        public Criteria andCarddefEqualTo(Integer value) {
            addCriterion("CardDef =", value, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefNotEqualTo(Integer value) {
            addCriterion("CardDef <>", value, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefGreaterThan(Integer value) {
            addCriterion("CardDef >", value, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardDef >=", value, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefLessThan(Integer value) {
            addCriterion("CardDef <", value, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefLessThanOrEqualTo(Integer value) {
            addCriterion("CardDef <=", value, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefIn(List<Integer> values) {
            addCriterion("CardDef in", values, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefNotIn(List<Integer> values) {
            addCriterion("CardDef not in", values, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefBetween(Integer value1, Integer value2) {
            addCriterion("CardDef between", value1, value2, "carddef");
            return (Criteria) this;
        }

        public Criteria andCarddefNotBetween(Integer value1, Integer value2) {
            addCriterion("CardDef not between", value1, value2, "carddef");
            return (Criteria) this;
        }

        public Criteria andCardisykdtIsNull() {
            addCriterion("CardIsYKDT is null");
            return (Criteria) this;
        }

        public Criteria andCardisykdtIsNotNull() {
            addCriterion("CardIsYKDT is not null");
            return (Criteria) this;
        }

        public Criteria andCardisykdtEqualTo(Integer value) {
            addCriterion("CardIsYKDT =", value, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtNotEqualTo(Integer value) {
            addCriterion("CardIsYKDT <>", value, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtGreaterThan(Integer value) {
            addCriterion("CardIsYKDT >", value, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardIsYKDT >=", value, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtLessThan(Integer value) {
            addCriterion("CardIsYKDT <", value, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtLessThanOrEqualTo(Integer value) {
            addCriterion("CardIsYKDT <=", value, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtIn(List<Integer> values) {
            addCriterion("CardIsYKDT in", values, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtNotIn(List<Integer> values) {
            addCriterion("CardIsYKDT not in", values, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtBetween(Integer value1, Integer value2) {
            addCriterion("CardIsYKDT between", value1, value2, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardisykdtNotBetween(Integer value1, Integer value2) {
            addCriterion("CardIsYKDT not between", value1, value2, "cardisykdt");
            return (Criteria) this;
        }

        public Criteria andCardistkenIsNull() {
            addCriterion("CardIsTKEN is null");
            return (Criteria) this;
        }

        public Criteria andCardistkenIsNotNull() {
            addCriterion("CardIsTKEN is not null");
            return (Criteria) this;
        }

        public Criteria andCardistkenEqualTo(Integer value) {
            addCriterion("CardIsTKEN =", value, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenNotEqualTo(Integer value) {
            addCriterion("CardIsTKEN <>", value, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenGreaterThan(Integer value) {
            addCriterion("CardIsTKEN >", value, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardIsTKEN >=", value, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenLessThan(Integer value) {
            addCriterion("CardIsTKEN <", value, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenLessThanOrEqualTo(Integer value) {
            addCriterion("CardIsTKEN <=", value, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenIn(List<Integer> values) {
            addCriterion("CardIsTKEN in", values, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenNotIn(List<Integer> values) {
            addCriterion("CardIsTKEN not in", values, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenBetween(Integer value1, Integer value2) {
            addCriterion("CardIsTKEN between", value1, value2, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardistkenNotBetween(Integer value1, Integer value2) {
            addCriterion("CardIsTKEN not between", value1, value2, "cardistken");
            return (Criteria) this;
        }

        public Criteria andCardloverIsNull() {
            addCriterion("CardLover is null");
            return (Criteria) this;
        }

        public Criteria andCardloverIsNotNull() {
            addCriterion("CardLover is not null");
            return (Criteria) this;
        }

        public Criteria andCardloverEqualTo(Integer value) {
            addCriterion("CardLover =", value, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverNotEqualTo(Integer value) {
            addCriterion("CardLover <>", value, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverGreaterThan(Integer value) {
            addCriterion("CardLover >", value, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverGreaterThanOrEqualTo(Integer value) {
            addCriterion("CardLover >=", value, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverLessThan(Integer value) {
            addCriterion("CardLover <", value, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverLessThanOrEqualTo(Integer value) {
            addCriterion("CardLover <=", value, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverIn(List<Integer> values) {
            addCriterion("CardLover in", values, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverNotIn(List<Integer> values) {
            addCriterion("CardLover not in", values, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverBetween(Integer value1, Integer value2) {
            addCriterion("CardLover between", value1, value2, "cardlover");
            return (Criteria) this;
        }

        public Criteria andCardloverNotBetween(Integer value1, Integer value2) {
            addCriterion("CardLover not between", value1, value2, "cardlover");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ygodata
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 03 23:10:22 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ygodata
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}