package cn.com.helloclyde.ygoService.mapper.model;

public class Ygodata {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata._id
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardID
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardStarNum
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer cardstarnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardAtk
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer cardatk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardDef
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer carddef;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardIsYKDT
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer cardisykdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardIsTKEN
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer cardistken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ygodata.CardLover
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    private Integer cardlover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata._id
     *
     * @return the value of ygodata._id
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata._id
     *
     * @param id the value for ygodata._id
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardID
     *
     * @return the value of ygodata.CardID
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardID
     *
     * @param cardid the value for ygodata.CardID
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardid(Integer cardid) {
        this.cardid = cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardStarNum
     *
     * @return the value of ygodata.CardStarNum
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCardstarnum() {
        return cardstarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardStarNum
     *
     * @param cardstarnum the value for ygodata.CardStarNum
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardstarnum(Integer cardstarnum) {
        this.cardstarnum = cardstarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardAtk
     *
     * @return the value of ygodata.CardAtk
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCardatk() {
        return cardatk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardAtk
     *
     * @param cardatk the value for ygodata.CardAtk
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardatk(Integer cardatk) {
        this.cardatk = cardatk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardDef
     *
     * @return the value of ygodata.CardDef
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCarddef() {
        return carddef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardDef
     *
     * @param carddef the value for ygodata.CardDef
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCarddef(Integer carddef) {
        this.carddef = carddef;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardIsYKDT
     *
     * @return the value of ygodata.CardIsYKDT
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCardisykdt() {
        return cardisykdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardIsYKDT
     *
     * @param cardisykdt the value for ygodata.CardIsYKDT
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardisykdt(Integer cardisykdt) {
        this.cardisykdt = cardisykdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardIsTKEN
     *
     * @return the value of ygodata.CardIsTKEN
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCardistken() {
        return cardistken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardIsTKEN
     *
     * @param cardistken the value for ygodata.CardIsTKEN
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardistken(Integer cardistken) {
        this.cardistken = cardistken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ygodata.CardLover
     *
     * @return the value of ygodata.CardLover
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public Integer getCardlover() {
        return cardlover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ygodata.CardLover
     *
     * @param cardlover the value for ygodata.CardLover
     *
     * @mbggenerated Fri Mar 03 23:10:22 CST 2017
     */
    public void setCardlover(Integer cardlover) {
        this.cardlover = cardlover;
    }
}